/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * ClauseGuard API
 * Grounded Contract Review API with Structured Extraction, Hybrid Retrieval & Verifiable Citations
 * Service version: 0.1.0
 */
import { FormData } from "https://jslib.k6.io/formdata/0.0.2/index.js";

import { URL } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response, ResponseBody } from "k6/http";

/**
 * Request payload for POST /ask.
 */
export interface AskRequest {
  document_id: string;
  /**
   * Legal or procurement question regarding the contract.
   * @minLength 5
   * @maxLength 2000
   */
  question: string;
}

export interface BodyUploadDocumentApiV1DocumentsPost {
  /** PDF contract file to ingest */
  file: string;
}

/**
 * Exact quote from the contract text. Must be verbatim from source.
 */
export type ClauseResultDetailSchemaVerbatimQuote = string | null;

/**
 * Plain-language concise summary of what this clause entails.
 */
export type ClauseResultDetailSchemaSummary = string | null;

/**
 * Page number where the clause appears in the contract.
 */
export type ClauseResultDetailSchemaPageNumber = number | null;

export type ClauseResultDetailSchemaId = string | null;

export type ClauseResultDetailSchemaSourceChunkId = string | null;

/**
 * Detail schema returned to clients with programmatic verification flags.
 */
export interface ClauseResultDetailSchema {
  clause_type: ClauseType;
  is_present: boolean;
  /** Exact quote from the contract text. Must be verbatim from source. */
  verbatim_quote?: ClauseResultDetailSchemaVerbatimQuote;
  /** Plain-language concise summary of what this clause entails. */
  summary?: ClauseResultDetailSchemaSummary;
  /** Page number where the clause appears in the contract. */
  page_number?: ClauseResultDetailSchemaPageNumber;
  /**
   * Model confidence score between 0.0 and 1.0.
   * @minimum 0
   * @maximum 1
   */
  confidence?: number;
  id?: ClauseResultDetailSchemaId;
  citation_verified?: boolean;
  source_chunk_id?: ClauseResultDetailSchemaSourceChunkId;
  repair_attempts?: number;
  used_fallback?: boolean;
}

export type ClauseType = (typeof ClauseType)[keyof typeof ClauseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClauseType = {
  termination: "termination",
  liability_cap: "liability_cap",
  indemnity: "indemnity",
  auto_renewal: "auto_renewal",
  governing_law: "governing_law",
  confidentiality: "confidentiality",
  ip_ownership: "ip_ownership",
  non_compete: "non_compete",
  force_majeure: "force_majeure",
  assignment: "assignment",
} as const;

export type DocumentStatusResponseStatus =
  (typeof DocumentStatusResponseStatus)[keyof typeof DocumentStatusResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentStatusResponseStatus = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  ALREADY_EXISTS: "ALREADY_EXISTS",
} as const;

export type DocumentStatusResponseTotalPages = number | null;

export type DocumentStatusResponseTotalChunks = number | null;

export type DocumentStatusResponseErrorMessage = string | null;

/**
 * Response returned upon GET /documents/{id}.
 */
export interface DocumentStatusResponse {
  id: string;
  filename: string;
  content_hash: string;
  status: DocumentStatusResponseStatus;
  total_pages: DocumentStatusResponseTotalPages;
  total_chunks: DocumentStatusResponseTotalChunks;
  error_message: DocumentStatusResponseErrorMessage;
  created_at: string;
  updated_at: string;
}

export type DocumentUploadResponseJobId = string | null;

export type DocumentUploadResponseStatus =
  (typeof DocumentUploadResponseStatus)[keyof typeof DocumentUploadResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentUploadResponseStatus = {
  PENDING: "PENDING",
  ALREADY_EXISTS: "ALREADY_EXISTS",
} as const;

/**
 * Response returned upon POST /documents upload.
 */
export interface DocumentUploadResponse {
  document_id: string;
  job_id: DocumentUploadResponseJobId;
  status: DocumentUploadResponseStatus;
  message: string;
}

/**
 * Request payload for POST /extract.
 */
export interface ExtractionRequest {
  document_id: string;
  /** List of clause types to extract. Defaults to all 10 standard clauses. */
  clause_types?: ClauseType[];
  /** Prompt template version to use */
  prompt_version?: string;
}

export type ExtractionResponseStatus =
  (typeof ExtractionResponseStatus)[keyof typeof ExtractionResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtractionResponseStatus = {
  COMPLETED: "COMPLETED",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
} as const;

/**
 * Response returned upon POST /extract and GET /extractions/{id}.
 */
export interface ExtractionResponse {
  extraction_id: string;
  document_id: string;
  status: ExtractionResponseStatus;
  model_id: string;
  prompt_version: string;
  clause_results: ClauseResultDetailSchema[];
  cost_usd: number;
  input_tokens: number;
  output_tokens: number;
  latency_ms: number;
  cache_hit: boolean;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type ExtractClausesApiV1ExtractPostHeaders = {
  "x-request-id"?: string | null;
};

export type AskQuestionApiV1AskPostHeaders = {
  "x-request-id"?: string | null;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class ClauseGuardAPIClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  /**
   * @summary Health check endpoint
   */
  healthCheckApiV1HealthGet(requestParameters?: Params): {
    response: Response;
    data: ResponseBody;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/health`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "health_check_api_v1_health_get",
    };
  }

  /**
   * @summary Upload contract PDF for ingestion
   */
  uploadDocumentApiV1DocumentsPost(
    bodyUploadDocumentApiV1DocumentsPost: BodyUploadDocumentApiV1DocumentsPost,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DocumentUploadResponse;
    operationId: string;
  } {
    const formData = new FormData();
    formData.append(`file`, bodyUploadDocumentApiV1DocumentsPost.file);

    const k6url = new URL(this.cleanBaseUrl + `/api/v1/documents`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("POST", k6url.toString(), formData.body(), {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        "Content-Type": "multipart/form-data; boundary=" + formData.boundary,
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "upload_document_api_v1_documents_post",
    };
  }

  /**
   * @summary Get document ingestion status and metadata
   */
  getDocumentApiV1DocumentsDocumentIdGet(
    documentId: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: DocumentStatusResponse;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl + `/api/v1/documents/${documentId}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_document_api_v1_documents__document_id__get",
    };
  }

  /**
   * @summary Extract structured clauses from contract
   */
  extractClausesApiV1ExtractPost(
    extractionRequest: ExtractionRequest,
    headers?: ExtractClausesApiV1ExtractPostHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ExtractionResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/extract`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(extractionRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "extract_clauses_api_v1_extract_post",
    };
  }

  /**
   * @summary Get extraction result by ID
   */
  getExtractionApiV1ExtractExtractionIdGet(
    extractionId: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: ExtractionResponse;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl + `/api/v1/extract/${extractionId}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "get_extraction_api_v1_extract__extraction_id__get",
    };
  }

  /**
   * @summary Ask a grounded question about a contract (Server-Sent Events streaming)
   */
  askQuestionApiV1AskPost(
    askRequest: AskRequest,
    headers?: AskQuestionApiV1AskPostHeaders,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/ask`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(askRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
          // In the schema, headers can be of any type like number but k6 accepts only strings as headers, hence converting all headers to string
          ...Object.fromEntries(
            Object.entries(headers || {}).map(([key, value]) => [
              key,
              String(value),
            ]),
          ),
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "ask_question_api_v1_ask_post",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
